services:
  web:
    build: .
    ports:
      - "8080:80"
    volumes:
      - .:/var/www/html
    depends_on:
      - db
    networks:
      - app-network
    extra_hosts:
      - "localhost:172.20.0.2" # Remplace 172.20.0.2 par l'IP du service `db`

  db:
    image: mysql:8.0
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root_password
      MYSQL_DATABASE: cybergames
      MYSQL_USER: root
      MYSQL_PASSWORD:
    ports:
      - "3306:3306"
    volumes:
      - db_data:/var/lib/mysql
    networks:
      - app-network
    expose:
      - "3306"

volumes:
  db_data:

networks:
  app-network:
    driver: bridge
